version: '3'

services:
  web:
    build:
      context: .
      args:
        PROJECTNAME: $PROJECTNAME
        ROOT_FOLDER: $ROOT_FOLDER
    working_dir: /$ROOT_FOLDER/$PROJECTNAME/
    #tty: true
    volumes:
      - .:/$ROOT_FOLDER
    env_file:
      - .env
    command: gunicorn -b 0.0.0.0:8000 $PROJECTNAME.wsgi

  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - web

  db:
    build: ./postgres
    hostname: db
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data/
    depends_on:
      - web
      - nginx
